apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-deployment
  namespace: jellyfish-agencysite
  labels:
    app: php-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: sample-php
        image: us.gcr.io/jellyfish-agencysite/jellyfish/agencysite/dev/sample-php:7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
